name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the feature
      placeholder: Summarize the feature in one paragraph...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Currently, users cannot...
        This makes it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        I would like to be able to...
        The feature should work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        I considered...
        Another approach could be...

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which module would this feature belong to?
      options:
        - POS (Point of Sale)
        - Inventory
        - Accounting
        - CRM
        - Dashboard
        - Settings
        - AI Assistant
        - Queue Board
        - New Module
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocking core functionality)
        - High (important for many users)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        As a [role], I want to [action] so that [benefit]...

        Example:
        As a pharmacist, I want to scan multiple items at once
        so that I can serve customers faster during peak hours.

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If you have any mockups or visual references, attach them here
      placeholder: Drag and drop images here...

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details or constraints to consider?
      placeholder: |
        This might require...
        We should consider...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Would you like to contribute to this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help test this feature
        - label: I can provide feedback during development

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: Additional information...

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: I have read the roadmap and this feature is not already planned
          required: true
        - label: I have provided all relevant information
          required: true
